### ISSUE TITLE
Create Component: Search bar

### ISSUE THREAD

**Issue by EngineerFaunce** [DylanBulmer/EngineeringEngineers#19]
The main search bar located at the top of the page.

![search-bar](https://user-images.githubusercontent.com/16312436/75788504-51c98580-5d36-11ea-835b-04e0bbe82f68.png)

**Comment by NathanRGagnon** [comment]
fix scroll bar on the searchbar

**Comment by NathanRGagnon** [comment]
Fixed the scroll bar
