### ISSUE TITLE
Design Component: Login Overlay

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#24]

**Comment by SKaplanOfficial** [comment]
Here's what I've come up with, based off of Dylan's initial design:
![sign-in](https://user-images.githubusercontent.com/7865925/75829603-ab54a300-5d7c-11ea-84ad-16e0c41730e7.png)

Feedback desired!

**Comment by EngineerFaunce** [comment]
Couple points:
* Remove the period in the "Remember me." text field
* Potentially change the color of the "Sign In" button. I feel red should be reserved for a logout button instead

Other than that, it looks good. Also should we remove issue #20 since it appears to be a duplicate?

**Comment by EngineerFaunce** [comment]
Here are some changes I made:
![Login Overlay](https://user-images.githubusercontent.com/16312436/76998903-31035180-692c-11ea-86d4-a7db96275a3b.png)

I added the `Recover Account` button because it was mentioned in the log in use case description and would appreciate further feedback.

**Comment by SKaplanOfficial** [comment]
@EngineerFaunce good catch. Looks good.
