### ISSUE TITLE
Design Page: Registration

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#27]

**Comment by bpatashnik** [comment]
<img width="932" alt="Screen Shot 2020-03-10 at 12 57 39 PM" src="https://user-images.githubusercontent.com/60401615/76338450-151a0300-62cf-11ea-99a4-9bbbd6d1fd7f.png">

**Comment by EngineerFaunce** [comment]
Looks good to me.

**Comment by SKaplanOfficial** [comment]
The gradient on the "Create Account" button is a bit much, but otherwise, it looks good.
