### ISSUE TITLE
Design Video Viewing Page

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#29]

**Comment by EngineerFaunce** [comment]
Need critique:

![Video Page](https://user-images.githubusercontent.com/16312436/76268216-c83d1a80-6243-11ea-90a0-0d3905ae38b3.png)

**Comment by SKaplanOfficial** [comment]
Rounding of 8 pixels should be more consistent

**Comment by NathanRGagnon** [comment]
There's no button to add a new comment

**Comment by NathanRGagnon** [comment]
The share and follow buttons are a bit large

**Comment by EngineerFaunce** [comment]
Here is a rough sketch of what the group came up with after feedback:
![ui sketch](https://user-images.githubusercontent.com/16312436/76268806-b8263a80-6245-11ea-8328-0bd63c140573.png)

**Comment by EngineerFaunce** [comment]
Here is the most recent iteration on the video page mockup:

![video-page](https://user-images.githubusercontent.com/16312436/76435864-ed3da480-638d-11ea-8a65-091caa957924.png)

**Comment by SKaplanOfficial** [comment]
With this complete, creating a mockup of the community comments tab might be good, as it should probably look somewhat different from the general comments tab. I've created a new issue for this: #34
