### ISSUE TITLE
SRS: Review Section 2.4- "Operating Environment"

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#30]
Added the following requirements:

- REQ-OE-1: The system shall maintain standard functionality on all Windows-brand operating systems still within the support period of their manufacturer as of March 2020.
- REQ-OE-2: The system shall maintain standard functionality on all MacOS-brand operating systems still within the support period of their manufacturer as of March 2020.
- REQ-OE-3: The system shall maintain standard functionality on all Android-brand operating systems still within the support period of their manufacturer as of March 2020.
- REQ-OE-4: The system shall maintain standard functionality on all iOS-brand operating systems still within the support period of their manufacturer as of March 2020.
- REQ-OE-5: The system shall maintain standard functionality on all Linux-based PC operating systems still within the support period of their manufacturer as of March 2020.
- REQ-OE-6: The system shall maintain standard functionality on all web browsers still within the support period of their manufacturer as of March 2020.
- REQ-OE-7: The system shall maintain standard functionality regardless of whether a user has Adobe Flash installed.
- REQ-OE-8: The system shall maintain standard functionality regardless of whether a user has an ad-blocking browser extension installed.
- REQ-OE-9: The system shall maintain standard functionality regardless of whether a user has an extension that blocks location tracking installed.
- REQ-OE-10: The system shall display a homepage organized for a non-registered user that displays trending communities.

**Comment by EngineerFaunce** [comment]
Looks good to me! Very specific in what types of machines the application will work with.

**Comment by SKaplanOfficial** [comment]
> Looks good to me! Very specific in what types of machines the application will work with.

Is that good or bad? I figured she would prefer it to be measurable rather than just "all modern operating systems" but maybe I went overboard.

**Comment by EngineerFaunce** [comment]
> 
> Is that good or bad? I figured she would prefer it to be measurable rather than just "all modern operating systems" but maybe I went overboard.

It's a good thing since it sets standards for how the application will run.
