### ISSUE TITLE
Documentation: Domain Model

### ISSUE THREAD

**Issue by EngineerFaunce** [DylanBulmer/EngineeringEngineers#36]
Here is the revised domain model document. I broke the domain model into separate diagrams in hopes of reducing complexity. Most of the attributes for classes were gathered from the database design. We will also probably need to update this again as the deliverable 3 deadline approaches.

[EngineeringEngineers_Deliverable_3_DomainModel.pdf](https://github.com/DylanBulmer/EngineeringEngineers/files/4418065/EngineeringEngineers_Deliverable_3_DomainModel.pdf)

**Comment by DylanBulmer** [comment]
I disagree with Login/Logout resulting with void, these functions need to result in something (like a boolean) in order for the react service to give an adequate response to the user, ie say Logout Successful, or display the correct screen when logging in. 

Should a Community Owner also be able to archive and unarchive a community?

I do like the fact that you used the Database model data for populating this document.
