### ISSUE TITLE
Documentation: Configuration Management Plan

### ISSUE THREAD

**Issue by EngineerFaunce** [DylanBulmer/EngineeringEngineers#39]
It includes:
* Software configuration management plan which follows IEEE 828-2005 standard and needs to have the following sections:
  * Introduction – Describes the plan’s purpose, scope of application, key terms, and references.
  * SCM Management (Who?) – Identifies the responsibilities and authorities for managing and accomplishing the planned SCM activities.
  * SCM Activities (What?) – Identifies all activities to be performed in applying to the project.
  * SCM Schedule (When?) – Establishes required coordination of SCM activities with other activities in the project.
  * SCM Resources (How?) – Identifies tools and physical and human resources required for the execution of the plan.
  * SCM Plan Maintenance – Identifies how the Plan will be kept current while in effect.

**Comment by DylanBulmer** [comment]
Never mind, I don't think its complete.....
