### ISSUE TITLE
Component Requirements: Card

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#41]
Need some people to review [this wiki page](https://github.com/DylanBulmer/EngineeringEngineers/wiki/Card-Component) and add information as needed? Want to have a good idea of what to include in the component before making it.

**Comment by EngineerFaunce** [comment]
Added the following to the `Video Card` section:
* Video cards shall display the user who uploaded the provided video.
* Video cards shall optionally display the community the provided video was posted to.
