### ISSUE TITLE
Sidebar fixes

### ISSUE THREAD

**Issue by NathanRGagnon** [DylanBulmer/EngineeringEngineers#48]
We need to make a container to stop the communities from entering an overflow state when the window is made smaller vertically

**Comment by NathanRGagnon** [comment]
We need to add a style parameter on the friends and communities buttons to set the colored gradients when we have the database working

**Comment by NathanRGagnon** [comment]
We need to create the other tabs as well once we have those systems working

**Comment by DylanBulmer** [comment]
> We need to make a container to stop the communities from entering an overflow state when the window is made smaller vertically

> We need to add a style parameter on the friends and communities buttons to set the colored gradients when we have the database working

Both of these have been completed in the Pull Request
