### ISSUE TITLE
Design: Sidebar - Chats Tab

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#52]
Need feedback on this design:
![sidebar-chats](https://user-images.githubusercontent.com/7865925/79058311-6bfe5980-7c3a-11ea-822a-9aa7c2e640e3.png)

**Comment by SKaplanOfficial** [comment]
The skoot logo & bottom links were missing. Fixed here:
![sidebar-chats](https://user-images.githubusercontent.com/7865925/79058921-bafbbd00-7c41-11ea-996f-ee48eac317c3.png)

**Comment by EngineerFaunce** [comment]
Looks good.

I'd suggest having some kind of indicator that will let the user know if the last message in the chat is from them or their friend. This could be something like changing the color of the navigation link, or just adding a small dot.

For community chats, the indicator should be present if the user was mentioned by another member in the chat.

Here's a rough sketch of my idea:
![suggestion](https://user-images.githubusercontent.com/16312436/79076345-6b5fd480-7cc7-11ea-8d13-f49b075f43c7.png)

**Comment by SKaplanOfficial** [comment]
@EngineerFaunce Good idea. Added that:
![sidebar-chats](https://user-images.githubusercontent.com/7865925/79093956-df2fca80-7d23-11ea-8a0c-76803da95777.png)
