### ISSUE TITLE
Design Change: Add some universal links to the sidebar

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#53]
When logged out, users have access to trending, discover, and "Home." Logged in users should have these as well (with "Dashboard" in place of "Home"). I added these to the design below. Thoughts?

![sidebar](https://user-images.githubusercontent.com/7865925/79058515-18413f80-7c3d-11ea-830e-1b9bbc1e0e3b.png)

**Comment by EngineerFaunce** [comment]
I think the universal links should sit above the two drop down menus. Other than that, it sounds good.
