### ISSUE TITLE
Design: Sidebar - Personal Tab

### ISSUE THREAD

**Issue by SKaplanOfficial** [DylanBulmer/EngineeringEngineers#54]
Need feedback on the personal tab of the sidebar, which includes relevant content-related and account-related actions & notifications from the user's personal community (the community associated with their profile). These notifications would also appear in the notifications tab but are more visible here.

![sidebar-personal](https://user-images.githubusercontent.com/7865925/79058903-9bfd2b00-7c41-11ea-8457-b2e0666220d4.png)

**Comment by EngineerFaunce** [comment]
I'm a little confused on the personal community. Is it a community about the user, or is it a community the user has chosen to highlight on their profile?

Other than that, this looks good!

**Comment by SKaplanOfficial** [comment]
@EngineerFaunce it is a community about the user, connected to the user's account. So everyone automatically has a community about them. At least, that's how I've been envisioning it.
