### ISSUE TITLE
Finalize detailed design document

### ISSUE THREAD

**Issue by DylanBulmer** [DylanBulmer/EngineeringEngineers#60]

**Comment by DylanBulmer** [comment]
The file that needs review is EngineeringEngineers_Deliverable_4_DesignPattern.pdf in the Deliverable 4 drive folder.

**Comment by EngineerFaunce** [comment]
The document in question:
[EngineeringEngineers_Deliverable_4_DesignPattern.pdf](https://github.com/DylanBulmer/EngineeringEngineers/files/4533150/EngineeringEngineers_Deliverable_4_DesignPattern.pdf)

Addresses all of the feedback from Deliverable 3. Looks good!
